### PR TITLE
allow insecure client configuration

### PR DESCRIPTION
**Pull request by ionos-landgraf-vin**
Fixes: Enable usage of reverseproxies #228

### CODE REVIEW

**Comment by ionos-landgraf-vin** [comment]
Thanks the new `IONOS_PINNED_CERT` does help me to implement what I needed.

**Comment by benschmi** [comment]
Hi @ionos-landgraf-vin , did you add this to the Terraform documentation?

**Comment by ionos-landgraf-vin** [comment]
Hi @benschmi maybe @cristiGuranIonos can answer if the documentation updated?

**Comment by benschmi** [comment]
Thanks @cristiGuranIonos. Shouldn't it also be part of https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs#usage ?

**Comment by cristiGuranIonos** [comment]
Very good point. Will add it there also.

**Pull request closed without merging**
